package proyecto1;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Eddy
 */
public class AddStation extends javax.swing.JFrame {

    
    private Proyecto1 mainClass;
    /**
     * Creates new form AddStation
     */
    public AddStation() {
        initComponents();
    }

    public AddStation(Proyecto1 mainClass, ModifyNetwork modifyNetwork){
        setLocationRelativeTo(modifyNetwork);
        this.mainClass = mainClass;
        initComponents();
        for (int i = 0; i < this.mainClass.red.getNombresLineas().length; i++) {
            this.SelectLinea.addItem(this.mainClass.red.getNombresLineas()[i]);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        SelectLinea = new javax.swing.JComboBox<>();
        SelectAdyacente = new javax.swing.JComboBox<>();
        SelectAdyacente2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 20, 40, -1));

        jButton2.setText("Agregar");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 100, 30));

        SelectLinea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SelectLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectLineaActionPerformed(evt);
            }
        });
        jPanel1.add(SelectLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, 30));

        SelectAdyacente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SelectAdyacente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectAdyacenteActionPerformed(evt);
            }
        });
        jPanel1.add(SelectAdyacente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 100, 30));

        SelectAdyacente2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SelectAdyacente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectAdyacente2ActionPerformed(evt);
            }
        });
        jPanel1.add(SelectAdyacente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SelectLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectLineaActionPerformed
        Linea l = this.mainClass.red.get(mainClass.red.buscarLineaPorNombre((String) SelectLinea.getSelectedItem()));
        for (int i = 0; i < l.getTamArreglo(); i++) {
            this.SelectAdyacente.addItem(l.get(i).getNombre());
        }
    }//GEN-LAST:event_SelectLineaActionPerformed

    private void SelectAdyacenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectAdyacenteActionPerformed
        Linea l = this.mainClass.red.get(mainClass.red.buscarLineaPorNombre((String) SelectLinea.getSelectedItem()));
        Parada p = l.get(l.buscarParadaPorNombre((String)this.SelectAdyacente.getSelectedItem()));
        this.SelectAdyacente2.addItem(l.get(l.buscarParadaPorNombre(p.getNombre())-1).getNombre());
        this.SelectAdyacente2.addItem(l.get(l.buscarParadaPorNombre(p.getNombre())-1).getNombre());   

    }//GEN-LAST:event_SelectAdyacenteActionPerformed

    private void SelectAdyacente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectAdyacente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectAdyacente2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SelectAdyacente;
    private javax.swing.JComboBox<String> SelectAdyacente2;
    private javax.swing.JComboBox<String> SelectLinea;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
