package proyecto1;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Eddy
 */
public class MainMenu extends javax.swing.JFrame {

    
    private Proyecto1 mainClass;
    private MenuPrincipalForm menuPrincipalForm;
    

    /**
     * Creates new form MainMenu
     */
    public MainMenu(Proyecto1 mainClass, MenuPrincipalForm menuPrincipalForm) {
        setLocationRelativeTo(menuPrincipalForm);
        this.mainClass = mainClass;
        this.menuPrincipalForm = menuPrincipalForm;
        initComponents();
        this.NetName.setText(this.mainClass.red.getNombre());
    }

    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        Exit = new javax.swing.JButton();
        Radius = new javax.swing.JLabel();
        changeRadius = new javax.swing.JButton();
        NetName = new javax.swing.JLabel();
        CoverManagementBtn = new javax.swing.JButton();
        SelectFileBtn = new javax.swing.JButton();
        ModifyNetworkBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit.setText("X");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 30, -1));

        Radius.setForeground(new java.awt.Color(0, 0, 0));
        Radius.setText("Radio de Cobertura: ");
        jPanel1.add(Radius, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 20));

        changeRadius.setText("Cambiar Radio");
        changeRadius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeRadiusActionPerformed(evt);
            }
        });
        jPanel1.add(changeRadius, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        NetName.setForeground(new java.awt.Color(0, 0, 0));
        NetName.setText("a");
        jPanel1.add(NetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 50, 20));

        CoverManagementBtn.setText("Manejo de Cobertura");
        CoverManagementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoverManagementBtnActionPerformed(evt);
            }
        });
        jPanel1.add(CoverManagementBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 140, 30));

        SelectFileBtn.setText("Cambio de Red");
        SelectFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectFileBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SelectFileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 140, 30));

        ModifyNetworkBtn.setText("Modificar Red");
        ModifyNetworkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyNetworkBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ModifyNetworkBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 140, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void CoverManagementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoverManagementBtnActionPerformed
        CoverManagement coverManagement = new CoverManagement(mainClass, this);
        coverManagement.setVisible(true);
    }//GEN-LAST:event_CoverManagementBtnActionPerformed

    private void ModifyNetworkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyNetworkBtnActionPerformed
        ModifyNetwork modifyNetwork = new ModifyNetwork(mainClass, this);
        modifyNetwork.setVisible(true);
    }//GEN-LAST:event_ModifyNetworkBtnActionPerformed

    private void SelectFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectFileBtnActionPerformed
        SeleccionarArchivoForm seleccionarArchivoForm = new SeleccionarArchivoForm(mainClass, menuPrincipalForm, this);
        seleccionarArchivoForm.setVisible(true);
    }//GEN-LAST:event_SelectFileBtnActionPerformed

    private void changeRadiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeRadiusActionPerformed
        ChangeRadius changeRadius = new ChangeRadius(mainClass, this);
        changeRadius.setVisible(true);
    }//GEN-LAST:event_changeRadiusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CoverManagementBtn;
    private javax.swing.JButton Exit;
    private javax.swing.JButton ModifyNetworkBtn;
    private javax.swing.JLabel NetName;
    private javax.swing.JLabel Radius;
    private javax.swing.JButton SelectFileBtn;
    private javax.swing.JButton changeRadius;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
