/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1;

import javax.swing.JOptionPane;

public class VentanaAgregarLinea extends javax.swing.JFrame {
    /**
     * Referencias a la clase principal y a la ventana principal.
     */
    private Proyecto1 mainClass;
    private VentanaPrincipal ventanaPrincipal;
    /**
     * Se guardan el nombre de la línea y las paradas.
     */
    private String nombreLinea = null;
    private String[] paradas = null;

    /**
     * Creates new form VentanaAgregarLinea
     */

    public VentanaAgregarLinea(Proyecto1 mainClass, VentanaPrincipal ventanaPrincipal) {
        this.mainClass = mainClass;
        this.ventanaPrincipal = ventanaPrincipal;
        setLocationRelativeTo(ventanaPrincipal);
        initComponents();
    }

    public VentanaAgregarLinea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        textNombreLinea = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        scrollPaneParadas = new javax.swing.JScrollPane();
        textAreaParadas = new javax.swing.JTextArea();
        scrollPaneInfoLinea = new javax.swing.JScrollPane();
        textAreaInfoLinea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Nombre Línea:");

        textNombreLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreLineaActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel2.setText("Paradas:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jLabel3.setText("Nombres de Paradas: separadas por coma o por una nueva línea.");

        textAreaParadas.setColumns(20);
        textAreaParadas.setRows(5);
        scrollPaneParadas.setViewportView(textAreaParadas);

        textAreaInfoLinea.setEditable(false);
        textAreaInfoLinea.setColumns(20);
        textAreaInfoLinea.setRows(5);
        scrollPaneInfoLinea.setViewportView(textAreaInfoLinea);

        jLabel4.setText("Información de la línea a agregar:");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jLabel5.setText("Transferencias en formato Parda1:Parada2");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jLabel6.setText("Los nombres son sencibles a Mayúsculas y Minúsculas. ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(scrollPaneInfoLinea)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(scrollPaneParadas)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(textNombreLinea,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 304,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addComponent(btnAceptar)
                                                .addGap(56, 56, 56)
                                                .addComponent(btnCancelar))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(129, 129, 129)
                                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 103,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textNombreLinea, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPaneParadas, javax.swing.GroupLayout.PREFERRED_SIZE, 243,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgregar)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPaneInfoLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 308,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(btnAceptar, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnCancelar))
                                .addGap(20, 20, 20)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNombreLineaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textNombreLineaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_textNombreLineaActionPerformed

    /**
     * Manejador del evento de presionar el botón de agregar una nueva linea y las
     * paradas, y las muestra en el TextArea, para que finalmente, el usuario
     * confirme que son los datos correctos.
     * 
     * @param evt
     */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAgregarActionPerformed
        if (textNombreLinea.getText() == null || textAreaParadas == null) {
            JOptionPane.showMessageDialog(this, "Tiene que haber un nombre de línea y por lo menos una parada!");
            textNombreLinea.setText("");
            textAreaParadas.setText("");
            return;
        }
        if (textNombreLinea.getText().strip().length() == 0 || textAreaParadas.getText().strip().length() == 0) {
            JOptionPane.showMessageDialog(this, "Tiene que haber un nombre de línea y por lo menos una parada!");
            textNombreLinea.setText("");
            textAreaParadas.setText("");
            return;
        }
        this.nombreLinea = textNombreLinea.getText().strip();
        String paradas = textAreaParadas.getText().strip();
        paradas = paradas.strip().replace("\n", ",");
        String[] paradasArray = paradas.split(",");
        ArrayList<String> paradasList = new ArrayList<>();
        for (String parada : paradasArray) {
            if (parada.strip().length() == 0) {
                continue;
            }
            paradasList.agregar(parada.strip());
        }
        Set<String> paradasSet = new Set<>(paradasList);
        paradasList = paradasSet.toList();
        String[] aux = new String[paradasList.size()];
        for (int i = 0; i < paradasList.size(); i++) {
            aux[i] = paradasList.get(i);
        }
        this.paradas = aux;

        textAreaInfoLinea.setText("");
        textAreaInfoLinea.append("Línea: " + this.nombreLinea + "\n");
        textAreaInfoLinea.append("       Paradas:\n");
        for (String parada : this.paradas) {
            textAreaInfoLinea.append("              " + parada + "\n");
        }
    }// GEN-LAST:event_btnAgregarActionPerformed

    /**
     * Manejador del evento de presionar el botón que confirma la creación de la
     * línea con sus paradas.
     * 
     * @param evt
     */
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAceptarActionPerformed
        if (!this.mainClass.red.agregarLinea(this.nombreLinea)) {
            JOptionPane.showMessageDialog(this,
                    "No se agregó la línea, verifica que no exista otra con el mismo nombre!");
            textNombreLinea.setText("");
            textAreaParadas.setText("");
            textAreaInfoLinea.setText("");
            return;
        }
        if (!this.mainClass.red.agregarParadas(this.nombreLinea, this.paradas)) {
            JOptionPane.showMessageDialog(this, "Hubo un problema agregando una parada en la línea!");
            textNombreLinea.setText("");
            textAreaParadas.setText("");
            textAreaInfoLinea.setText("");
            return;
        }
        this.mainClass.red.cargarGrafo();
        this.mainClass.red.cargarGsGraph();
        this.ventanaPrincipal.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_btnAceptarActionPerformed

    /**
     * Botón que cancela la creación de la línea.
     * 
     * @param evt
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarActionPerformed
        this.ventanaPrincipal.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosing
        this.ventanaPrincipal.setVisible(true);
    }// GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarLinea.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarLinea.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarLinea.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarLinea.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAgregarLinea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JScrollPane scrollPaneInfoLinea;
    private javax.swing.JScrollPane scrollPaneParadas;
    private javax.swing.JTextArea textAreaInfoLinea;
    private javax.swing.JTextArea textAreaParadas;
    private javax.swing.JTextField textNombreLinea;
    // End of variables declaration//GEN-END:variables
}
