/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1;

import javax.swing.JFrame;

public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Se mantiene una referencia a la clase principal para poder acceder a sus
     * objetos.
     */
    private Proyecto1 mainClass;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * Constructor de la clase.
     * 
     * @param mainClass referencia a la clase principal
     */
    public VentanaPrincipal(Proyecto1 mainClass) {
        setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.mainClass = mainClass;
        setTitle("Menú Principal");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCargarArchivo = new javax.swing.JButton();
        btnAbrirVentanaManejadorGrafo = new javax.swing.JButton();
        btnAgregarLinea = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }

            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        btnCargarArchivo.setText("Cargar Archivo");
        btnCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarArchivoActionPerformed(evt);
            }
        });

        btnAbrirVentanaManejadorGrafo.setText("Mostrar Grafo");
        btnAbrirVentanaManejadorGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirVentanaManejadorGrafoActionPerformed(evt);
            }
        });

        btnAgregarLinea.setText("Agregar Línea");
        btnAgregarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLineaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(btnCargarArchivo)
                                        .addComponent(btnAgregarLinea)
                                        .addComponent(btnAbrirVentanaManejadorGrafo,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 113,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(74, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btnCargarArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 56,
                                        Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarLinea, javax.swing.GroupLayout.DEFAULT_SIZE, 57,
                                        Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAbrirVentanaManejadorGrafo, javax.swing.GroupLayout.DEFAULT_SIZE, 57,
                                        Short.MAX_VALUE)
                                .addGap(23, 23, 23)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Manejador del evento de pulsar el botón Cargar Archivo.
     * 
     * @param evt
     */
    private void btnCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCargarArchivoActionPerformed
        VentanaSeleccionarArchivo ventanaSeleccionarArchivo = new VentanaSeleccionarArchivo(mainClass, this);
        this.setVisible(false);
        ventanaSeleccionarArchivo.setVisible(true);
    }// GEN-LAST:event_btnCargarArchivoActionPerformed

    /**
     * Manejador del evento de ganar el foco en la ventana. Verifica que botones
     * deben estar habilitados
     * 
     * @param evt
     */
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowGainedFocus
        if (this.mainClass.red.grafoVacio() || this.mainClass.red.gsGraphVacio()) {
            this.btnAbrirVentanaManejadorGrafo.setEnabled(false);
            this.btnAgregarLinea.setEnabled(false);
        } else {
            this.btnAbrirVentanaManejadorGrafo.setEnabled(true);
            this.btnAgregarLinea.setEnabled(true);
        }
    }// GEN-LAST:event_formWindowGainedFocus

    /**
     * Manejador del evento de presionar el botón que abre la ventana del manejador
     * del grafo.
     * 
     * @param evt
     */
    private void btnAbrirVentanaManejadorGrafoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAbrirVentanaManejadorGrafoActionPerformed

        VentanaManejadorGrafo ventanaManejadorGrafo = new VentanaManejadorGrafo(mainClass, this);
        this.setVisible(false);
        ventanaManejadorGrafo.setVisible(true);
    }// GEN-LAST:event_btnAbrirVentanaManejadorGrafoActionPerformed

    /**
     * Manejador del evento de presionar el botón que abre la ventana de agregar
     * lineas a la red.
     * 
     * @param evt
     */
    private void btnAgregarLineaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAgregarLineaActionPerformed
        VentanaAgregarLinea ventanaAgregarLinea = new VentanaAgregarLinea(mainClass, this);
        this.setVisible(false);
        ventanaAgregarLinea.setVisible(true);
    }// GEN-LAST:event_btnAgregarLineaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirVentanaManejadorGrafo;
    private javax.swing.JButton btnAgregarLinea;
    private javax.swing.JButton btnCargarArchivo;
    // End of variables declaration//GEN-END:variables
}
